"""init database

Revision ID: 21aefaf5e20d
Revises: 
Create Date: 2020-11-19 21:56:50.284247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aefaf5e20d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wisata',
    sa.Column('id_wisata', sa.Integer(), nullable=False),
    sa.Column('nama_wisata', sa.String(), nullable=False),
    sa.Column('alamat_wisata', sa.String(), nullable=True),
    sa.Column('deskripsi_wisata', sa.Text(), nullable=True),
    sa.Column('gambar_wisata', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_wisata')
    )
    op.create_index(op.f('ix_wisata_id_wisata'), 'wisata', ['id_wisata'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wisata_id_wisata'), table_name='wisata')
    op.drop_table('wisata')
    # ### end Alembic commands ###
