"""change model

Revision ID: 7e7761fe8ba9
Revises: 37085b5c6857
Create Date: 2020-10-29 13:56:39.152199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7761fe8ba9'
down_revision = '37085b5c6857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
